# Generated by Django 5.2.5

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
        ('matgroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Employee.employee')),
                ('mgrp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='matgroups.matgroup', to_field='mgrp_code')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('employee', 'mgrp_code')},
            },
        ),
    ]


