# Generated by Django 4.2 on 2025-12-12 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0019_alter_employee_email'),
        ('itemmaster', '0008_itemmaster_is_final'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='itemmaster.itemmaster'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('employee', 'item')},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='mgrp_code',
        ),
        migrations.CreateModel(
            name='SharedMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_users', to='itemmaster.itemmaster')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_materials', to='Employee.employee')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_materials', to='Employee.employee')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('shared_by', 'shared_with', 'item')},
            },
        ),
    ]
