# Generated by Django 4.2 on 2025-11-14 05:55

from django.db import migrations, models
import django.db.models.deletion


def clear_invalid_attribgrpid(apps, schema_editor):
    """Clear invalid attribgrpid values before converting to ForeignKey"""
    MatGroup = apps.get_model('matgroups', 'MatGroup')
    MatgAttributeItem = apps.get_model('matg_attributes', 'MatgAttributeItem')
    
    # Get all valid MatgAttributeItem IDs
    valid_ids = set(MatgAttributeItem.objects.values_list('id', flat=True))
    
    # Set attribgrpid to NULL for any MatGroup with invalid attribgrpid
    MatGroup.objects.exclude(attribgrpid__isnull=True).exclude(attribgrpid__in=valid_ids).update(attribgrpid=None)


def reverse_clear_invalid_attribgrpid(apps, schema_editor):
    """Reverse operation - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('matg_attributes', '0005_matgattributeitem_delete_matgattribute'),
        ('matgroups', '0008_alter_matgroup_mgrp_code'),
    ]

    operations = [
        # First, clear invalid attribgrpid values
        migrations.RunPython(clear_invalid_attribgrpid, reverse_clear_invalid_attribgrpid),
        # Then convert the field to ForeignKey
        migrations.AlterField(
            model_name='matgroup',
            name='attribgrpid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matgroups', to='matg_attributes.matgattributeitem'),
        ),
    ]
