# Generated by Django 4.2 on 2025-11-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matg_attributes', '0005_matgattributeitem_delete_matgattribute'),
        ('matgroups', '0009_alter_matgroup_attribgrpid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matgroup',
            name='attribgrpid',
        ),
        migrations.AddField(
            model_name='matgroup',
            name='attribgrpId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matg_attributes.matgattributeitem'),
        ),
    ]
