# Generated by Django 4.2 on 2025-11-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matgroups', '0010_remove_matgroup_attribgrpid_matgroup_attribgrpid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matgroup',
            name='is_service',
        ),
        migrations.AddField(
            model_name='matgroup',
            name='search_type',
            field=models.CharField(choices=[('service', 'Service'), ('Materials', 'Materials'), ('spares', 'Spares')], default='Materials', max_length=20),
        ),
    ]
