# Generated by Django 4.2 on 2026-03-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matgroups', '0011_remove_matgroup_is_service_matgroup_search_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='matgroup',
            name='uom_values',
            field=models.JSONField(blank=True, default=list, help_text='List of Unit of Measure values for this group'),
        ),
    ]
