# Generated by Django 4.2 on 2025-11-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0005_alter_itemmaster_mat_type_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmaster',
            options={'verbose_name': 'Item Master', 'verbose_name_plural': 'Item Masters'},
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='attributes',
            field=models.JSONField(default=dict, help_text="Stores selected attribute values for this material, based on MatGroup's attribute definitions"),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='item_desc',
            field=models.CharField(max_length=100),
        ),
    ]
