# Generated by Django 4.2 on 2025-11-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0006_alter_itemmaster_options_itemmaster_attributes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmaster',
            old_name='item_desc',
            new_name='short_name',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='notes',
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='long_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='mgrp_long_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='sap_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
