# Generated by Django 4.2 on 2025-11-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0007_rename_item_desc_itemmaster_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
