# Generated by Django 4.2 on 2025-11-18 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matgroups', '0010_remove_matgroup_attribgrpid_matgroup_attribgrpid'),
        ('requests', '0011_request_material_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='material_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_material_groups', to='matgroups.matgroup'),
        ),
    ]
