# Generated by Django 4.2 on 2025-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_alter_request_material_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='isread',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='tobeshown',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
