# Generated by Django 4.2 on 2025-11-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matg_attributes', '0003_alter_matgattribute_createdby_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matgattribute',
            options={'verbose_name': 'Material Group Attribute', 'verbose_name_plural': 'Material Group Attributes'},
        ),
        migrations.RemoveField(
            model_name='matgattribute',
            name='att_maxnamelen',
        ),
        migrations.RemoveField(
            model_name='matgattribute',
            name='attrib_maxtaglen',
        ),
        migrations.RemoveField(
            model_name='matgattribute',
            name='attrib_name',
        ),
        migrations.RemoveField(
            model_name='matgattribute',
            name='attrib_name_validation',
        ),
        migrations.RemoveField(
            model_name='matgattribute',
            name='attrib_printname',
        ),
        migrations.RemoveField(
            model_name='matgattribute',
            name='attrib_printpriority',
        ),
        migrations.RemoveField(
            model_name='matgattribute',
            name='attrib_tag_validation',
        ),
        migrations.RemoveField(
            model_name='matgattribute',
            name='attrib_tagname',
        ),
        migrations.AddField(
            model_name='matgattribute',
            name='attributes',
            field=models.JSONField(default=dict, help_text='JSON structure storing attribute names and their possible values'),
        ),
    ]
