# Generated by Django 4.2 on 2025-11-14 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matgroups', '0008_alter_matgroup_mgrp_code'),
        ('Employee', '0019_alter_employee_email'),
        ('matg_attributes', '0004_alter_matgattribute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatgAttributeItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=150)),
                ('possible_values', models.JSONField(default=list, help_text='Fixed allowed values for this attribute')),
                ('uom', models.CharField(blank=True, help_text='UOM for numeric dropdown attributes (optional)', max_length=50, null=True)),
                ('print_priority', models.IntegerField(blank=True, null=True)),
                ('validation', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matgitem_created', to='Employee.employee')),
                ('mgrp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_items', to='matgroups.matgroup')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matgitem_updated', to='Employee.employee')),
            ],
            options={
                'unique_together': {('mgrp_code', 'attribute_name')},
            },
        ),
        migrations.DeleteModel(
            name='MatgAttribute',
        ),
    ]
